### ISSUE TITLE
Komodor pods not deploying correctly

### ISSUE THREAD

**Issue by mikemcd3912** [aws-samples/eks-anywhere-addons#307]
**Describe the bug**
The Komodor pods are not reaching a ready state - They enter a crashback loop due to a 403 forbidden error on remote config (See Screenshots). @nirbenator can you confirm whether our software license has expired or if there is another reason for this error?

**Screenshots**
![image 2](https://github.com/user-attachments/assets/b1047942-f265-44ae-a9fb-55142662f4ce)
![image 3](https://github.com/user-attachments/assets/fead98b8-43bc-48d4-9a41-cf0c4154dc81)

**Comment by nirbenator** [comment]
Hey @mikemcd3912 
in order to validate ill need the value for 
```
  - secretKey: k8s-watcher-apiKey 
    remoteRef:
      key: komodor-secrets
      property: k8s-watcher-apiKey
  - secretKey: k8s-watcher-clusterName
    remoteRef:
      key: komodor-secrets
      property: k8s-watcher-clusterName
```
feel free to send them to me on slack
